DELETE FROM APP.COMPANY;
DELETE FROM APP.CUSTOMER;
DELETE FROM APP.COUPON;
DELETE FROM APP.COMPANY_COUPON;
DELETE FROM APP.CUSTOMER_COUPON;

SELECT * FROM APP.COMPANY;
SELECT * FROM APP.CUSTOMER;
SELECT * FROM APP.COUPON;
SELECT * FROM APP.COMPANY_COUPON;
SELECT * FROM APP.CUSTOMER_COUPON;



