DELETE FROM app.CUSTOMER_COUPON;
DELETE FROM app.COMPANY_COUPON;
DELETE FROM app.COMPANY;
DELETE FROM app.COUPON;
DELETE FROM app.CUSTOMER;


SELECT * FROM app.CUSTOMER_COUPON;
SELECT * FROM app.COMPANY_COUPON;
SELECT * FROM app.COMPANY;
SELECT * FROM app.COUPON;
SELECT * FROM app.CUSTOMER;


